trigger:
- main

pool:
  vmImage: 'windows-latest'  

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)/ropeworks'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
        
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MISTRAS Marketing Production (12c0b9b8-aef7-4c3c-b9fc-193f487d933f)'
    appType: 'webApp'
    appName: 'ropeworks'
    deployToSlotOrASE: true
    resourceGroupName: 'mistras-brand-websites'
    slotName: 'staging'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'zipDeploy'
